cc_binary(
        name = "etcdtool",
        srcs = ["etcd-tool.cpp"],
        deps = ["//src/mds/nameserver2",
                "//external:gflags",
                "//external:glog",
                "//external:brpc"]
        )
